USE [master]
GO

/****** Object:  Database [PCT]    Script Date: 2 oct. 2017 19:43:15 ******/
CREATE DATABASE [PCT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PCT', FILENAME = N'D:\Importante\Desarrollo\_Bases de datos\PCT\PCT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PCT_log', FILENAME = N'D:\Importante\Desarrollo\_Bases de datos\PCT\PCT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PCT] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PCT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PCT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PCT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PCT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PCT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PCT] SET ARITHABORT OFF 
GO

ALTER DATABASE [PCT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PCT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PCT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PCT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PCT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PCT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PCT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PCT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PCT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PCT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PCT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PCT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PCT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PCT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PCT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PCT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PCT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PCT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PCT] SET  MULTI_USER 
GO

ALTER DATABASE [PCT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PCT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PCT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PCT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PCT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PCT] SET QUERY_STORE = OFF
GO

USE [PCT]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PCT] SET  READ_WRITE 
GO


